name: emayer_cutter
description: "Emayer Cutter"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Network
  dio: ^5.8.0+1

  # Window
  window_manager: ^0.5.1

  # SVG
  flutter_svg: ^2.2.0

  # Provider
  provider: ^6.1.5

  # Router
  go_router: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/splash/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf

