import 'package:flutter/material.dart';

/// Project custom colors
final class CustomColorScheme {
  CustomColorScheme._();

  /// Light color scheme set
  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFFCFCFC),
      surfaceTint: Color(0xFF6750A4),
      onPrimary: Color(0xFF5B83A7),
      primaryContainer: Color(0xFFFFFFFF),
      onPrimaryContainer: Color(0xFF21005D),
      secondary: Color.fromRGBO(241, 241, 241, 1),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFF6F6F6),
      onSecondaryContainer: Color(0xFF1D192B),
      tertiary: Color(0xFF939393),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xFFFFD8E4),
      onTertiaryContainer: Color(0xFF31111D),
      error: Color(0xFFF23D3D),
      onError: Color(0xFF2A2D34),
      errorContainer: Color(0xFFF9DEDC),
      onErrorContainer: Color(0xFF410E0B),
      surface: Color(0xFFFFFBFE),
      onSurface: Color(0xFF1C1B1F),
      onSurfaceVariant: Color(0xFF49454F),
      outline: Color.fromARGB(255, 220, 220, 221),
      outlineVariant: Color(0xFFCAC4D0),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xFF313033),
      inversePrimary: Color(0xFFD0BCFF),
      primaryFixed: Color(0xffd0e4f7),
      onPrimaryFixed: Color(0xff001d33),
      primaryFixedDim: Color(0xff9fcaf0),
      onPrimaryFixedVariant: Color(0xff004580),
      secondaryFixed: Color(0xffdae2f1),
      onSecondaryFixed: Color(0xff1c2733),
      secondaryFixedDim: Color(0xffbcc8d9),
      onSecondaryFixedVariant: Color(0xff404b5a),
      tertiaryFixed: Color(0xfff2d9f7),
      onTertiaryFixed: Color(0xff2b1733),
      tertiaryFixedDim: Color(0xffd1aed8),
      onTertiaryFixedVariant: Color(0xff50345a),
      surfaceDim: Color(0xffe0e3ea),
      surfaceBright: Color(0xffffffff),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff3f6fa),
      surfaceContainer: Color(0xffebeff4),
      surfaceContainerHigh: Color(0xffe3e8ee),
      surfaceContainerHighest: Color(0xffdce2e9),
    );
  }

  /// Dark color scheme set
  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF1a1d21),
      surfaceTint: Color(0xFFD0BCFF),
      onPrimary: Color(0xFF381E72),
      primaryContainer: Color(0xFF23282F),
      onPrimaryContainer: Color(0xFFEADDFF),
      secondary: Color(0xFF393939),
      onSecondary: Color(0xFF171717),
      secondaryContainer: Color(0xFF404448),
      onSecondaryContainer: Color(0xFFE8DEF8),
      tertiary: Color(0xFFF1F1F1),
      onTertiary: Color(0xff492532),
      tertiaryContainer: Color(0xff633B48),
      onTertiaryContainer: Color(0xFFFFD8E4),
      error: Color(0xFFF23D3D),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xff8C1D18),
      onErrorContainer: Color(0xFFF9DEDC),
      surface: Color(0xff1C1B1F),
      onSurface: Color(0xFFE6E1E5),
      onSurfaceVariant: Color(0xFFCAC4D0),
      outline: Color(0xff938F99),
      outlineVariant: Color(0xff49454F),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xFFE6E1E5),
      inversePrimary: Color(0xff6750A4),
      primaryFixed: Color(0xffd0e4f7),
      onPrimaryFixed: Color(0xff001d33),
      primaryFixedDim: Color(0xff9fcaf0),
      onPrimaryFixedVariant: Color(0xff004580),
      secondaryFixed: Color(0xffdae2f1),
      onSecondaryFixed: Color(0xff1c2733),
      secondaryFixedDim: Color(0xffbcc8d9),
      onSecondaryFixedVariant: Color(0xff404b5a),
      tertiaryFixed: Color(0xfff2d9f7),
      onTertiaryFixed: Color(0xff2b1733),
      tertiaryFixedDim: Color(0xffd1aed8),
      onTertiaryFixedVariant: Color(0xff50345a),
      surfaceDim: Color(0xff191b1f),
      surfaceBright: Color(0xff383a3e),
      surfaceContainerLowest: Color(0xff0d0f12),
      surfaceContainerLow: Color(0xff17191c),
      surfaceContainer: Color(0xff1d1f22),
      surfaceContainerHigh: Color(0xff26292c),
      surfaceContainerHighest: Color(0xff303336),
    );
  }
}
